### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by cstrlln** [huklein/demuxmix#11]
Hi, I get this error while running demuxmix:

> dmm <-  demuxmix(hto = hto_counts, rna = rna_counts)
Error in while (iter < maxIter & abs(deltaLogLik/logLik) > tol) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In dnbinom(hto, mu = mu1, size = theta1) : NaNs produced
2: In dnbinom(hto, mu = mu2, size = theta2) : NaNs produced

any idea what might be causing it?
Thank you

**Comment by huklein** [comment]
Hello,
If the hto counts (n x m matrix) and the rna counts (m vector) look fine (integers, no NaN, etc.), could you send me your hto and rna counts as an Rdata file so that I can take a look? Or any other working example causing this error would be helpful too. Guessing from the warning message, either mu or theta converged to a non-meaningful value. I haven't seen that before. Do you get the same error when you run demuxmix without the RNA counts:
```demuxmix(hto = hto_counts, model = "naive")```

**Comment by cstrlln** [comment]
Yes, I got the same error when running without the RNA counts. Sure, I will setup the data, what email should I send them to?
I have noticed my count numbers for the HTO are lower from examples I have seen, so wondering if that can also affect? But you will see with the data.

**Comment by huklein** [comment]
You can use the email linked to my github ( hk2948 at cumc.columbia.edu ) Thanks!
