### ISSUE TITLE
Default value of pAcpt

### ISSUE THREAD

**Issue by PeteHaitch** [huklein/demuxmix#2]
How does **demumix** set the default/automatic value of `pAcpt()`?
I've noticed that it can vary across datasets and would like to better understand this behaviour.

**Comment by huklein** [comment]
The default "acceptance probability" `pAcpt = 0.9^n` depends on the number n of HTOs used, which usually equals the number of samples in most experimental designs. The rationale for choosing an acceptance probability depending on the number of HTOs is that pooling many samples increases demultiplexing complexity (2^n possible classes), leading either to a larger number of uncertain droplets or a larger error rate. Assuming a constant HTO library quality, pAcpt = 0.9^n  results in an approximately constant classification rate (at the cost of a larger error rate). Most users expect this behavior and are willing to accept a larger error rate (rather than losing a larger fraction of their data) when they pool many samples as they know about the increased demultiplexing complexity. Users afraid of demultiplexing errors usually only pool very few samples or do not pool at all.

Technically, the class probability in demuxmix is a product of the n probabilities of the droplet being positive or negative for the individual HTOs; thus, the probabilities will inevitably decrease with increasing n. Practically, in my experience, 0.9^n works well as a trade-off between classification error rate and singlet retrieval rate across a broad range of datasets. Most of the datasets I worked with pooled few samples (n<=4), and if the quality is high, changing pAcpt does not affect the results significantly since most droplets have probabilities very close to 1. Nevertheless, this is the most important demuxmix parameter (perhaps the only important one), and users should be aware of it because the willingness to accept some misclassified droplets may differ between experiments. Specifically, a single HTO of poor quality can negatively affect the probabilities of all droplets, and if the affected sample is precious, lowering pAcpt might be an option. In fact, pAcpt is the only demuxmix parameter I have occasionally changed in the past when working with real data. When I change pAcpt for a low-quality dataset, I usually look at the effect in the summary() output.
