### ISSUE TITLE
Error when running on data with very low counts for one hashtag

### ISSUE THREAD

**Issue by ghowitt** [huklein/demuxmix#7]
We have a data set where one of the samples has much lower counts than the rest of the samples in the batch (~50 cells vs 1000 cells for the other seven samples). Running demuxmix with `model = "naive" `on this data returns the following error:
`Error in while (iter < maxIter & abs(deltaLogLik/logLik) > tol) { :
missing value where TRUE/FALSE needed`

Running with `model = "auto"` returns this error:
`Error in glm.fitter(x = X, y = Y, w = w, start = start, etastart = etastart,  : 
  object 'fit' not found
In addition: Warning messages:
1: In dnbinom(hto, mu = mu1, size = theta1) : NaNs produced
2: In dnbinom(hto, mu = mu2, size = theta2) : NaNs produced
3: In glm.fitter(x = X, y = Y, w = w, start = start, etastart = etastart,  :
  no observations informative at iteration 1
4: glm.fit: algorithm did not converge `

All other parameters are default, though adjusting `tol` and `maxIter` in either direction resulted in the same error.

We have been able to run demuxmix successfully on other batches of similarly-prepared data, and if we exclude the hashtag with very few cells from the counts matrix it runs as normal. 

If you would like a copy of the data for testing purposes please let me know.

**Comment by huklein** [comment]
Hi,
Thanks for reporting this! I have an idea of what may happen. Still, if you can provide me with the data, that would be very helpful. Please post a link here or send it to my email address. <hansulrich.klein at gmail.com>

**Comment by ghowitt** [comment]
Thanks for the reply, I've attached two files which are the HTO counts for two separate captures on the same samples. 
[b4_c1_hto_counts.csv](https://github.com/huklein/demuxmix/files/10496054/b4_c1_hto_counts.csv)
[b4_c2_hto_counts.csv](https://github.com/huklein/demuxmix/files/10496055/b4_c2_hto_counts.csv)

**Comment by huklein** [comment]
Hello,
You were right, and the error message is related to the fact that only a very small fraction of droplets is tagged by one of the HTOs. I updated the package so that a better error message is given and an option to manually resolve the issue is provided. It will still need manual intervention as this situation is very uncommon (let me know if I am wrong), and the user should pay attention to it.

In detail, demuxmix uses an initial k-means clustering to obtain class labels with which the EM algorithm is initialized. The EM algorithm is fast and would work well with random start labels. However, the clustering is also used to label outliers with huge HTO read counts. This step is essential since the model uses ML estimates, and such outliers do have an effect.

Let's look at your data. I am using demuxmix version v1.1.1 (available at BiocDevel or GitHub) and you will need this new version to follow the solution outlined here:

```
library(demuxmix)

hto <- as.matrix(read.csv("b4_c1_hto_counts.csv", header = TRUE))
rowSums(hto)
# Human-HTO-6  Human-HTO-7  Human-HTO-9 Human-HTO-10 Human-HTO-12 Human-HTO-13 Human-HTO-14 Human-HTO-15 
#     4245910      1376870       175277      1119830      1004170       766301      1403748      4843327

set.seed(270123)
dmm <- demuxmix(hto, model = "naive")
Error in dmmFitNaive(hto = prepData$hto[!prepData$outlier], clusterInit = prepData$cluster[!prepData$outlier],  : 
  Invalid distribution parameters were derived from the initial clustering for HTO "Human-HTO-9". This usually indicates that i) a very small fraction of cells were tagged with this HTO, or ii) the HTO failed and does not show a bimodal distribution. Please verify the HTO's distribution in a histogram and run demuxmix with an initial manual clustering using the clusterInit parameter, if appropriate.
In addition: Warning messages:
1: In dnbinom(hto, mu = mu1, size = theta1) : NaNs produced
2: In dnbinom(hto, mu = mu2, size = theta2) : NaNs produced
```

There is still an error message, but a more helpful one. I will show later, that the k-means (k=2) clustering failed because there were so few and not well-separated positive cells. The simple solution is to look at the distribution of the HTO counts and define manual initial class labels:

```
hist(log10(hto["Human-HTO-9", ]))
```
![HTO-9-histogram](https://user-images.githubusercontent.com/29508973/215213392-3d540bf8-1010-47f4-979d-f14523d7ba29.png)

The HTO did not fail completely; there are some positive cells around 2. I will run demuxmix with an initial manual clustering for this HTO. I am using a threshold of 1.5, but the exact threshold should not matter as long as it is in a reasonable range.
```
manualInit <- rep(1, ncol(hto))
manualInit[hto["Human-HTO-9", ] >= 10^1.5] <- 2
table(manualInit)
manualInit
    1     2 
24696   333 

set.seed(270123)
dmm <- demuxmix(hto, model = "naive", clusterInit = list("Human-HTO-9"=manualInit))
summary(dmm)
          Class NumObs     RelFreq   MedProb     ExpFPs       FDR
1  Human-HTO-10    867 0.035960182 0.8305645  184.59235 0.2129093
2  Human-HTO-12   1795 0.074450436 0.8218607  393.93384 0.2194617
3  Human-HTO-13   2633 0.109207798 0.8949174  401.50886 0.1524910
4  Human-HTO-14   2085 0.086478640 0.8609772  384.93457 0.1846209
5  Human-HTO-15   2805 0.116341767 0.8273526  602.12688 0.2146620
6   Human-HTO-6   4837 0.200622148 0.8083611 1109.42500 0.2293622
7   Human-HTO-7   1402 0.058150145 0.8281378  298.31341 0.2127770
8   Human-HTO-9    214 0.008875985 0.8229565   48.13331 0.2249220
9       singlet  16638 0.690087101 0.8318182 3422.96821 0.2057320
10    multiplet   4776 0.198092078 0.7947950 1183.53707 0.2478093
11     negative   2696 0.111820821 0.7445732  773.62905 0.2869544
12    uncertain    919          NA        NA         NA        NA

plotDmmHistogram(dmm, hto = "Human-HTO-9", binwidth = 3) +
    ggplot2::coord_cartesian(xlim = c(0, 150), ylim = c(0, 0.008))
Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```
![HTO-9-DmmHistogram](https://user-images.githubusercontent.com/29508973/215219433-8f0af122-4dcd-4086-81ca-c0254d3c1441.png)

The dataset is undoubtedly not easy to demultiplex, but the model fit and results from demuxmix are reasonable. HTO-9 tagged an estimated 214 cells (only about 0.8% of the cells!).

Three notes:
1) The initial clustering (manual or automatic) is stored in a matrix in the demuxmix object for debugging:
```
all(dmm@clusterInit["Human-HTO-9", ] == manualInit)
[1] TRUE
```
2) We can run the k-means clustering separately to check that it really did not do well (too many positive cells). It basically split the neg binom distribution in half.
```
preproc <- demuxmix:::dmmPreprocess(hto["Human-HTO-9", ])
table(preproc$cluster)

    1     2 
15623  9406 
```
3) I finally wrote and submitted a manuscript. It will be on bioRxiv very soon and I will provide a link on the GitHub site. Please check back if you want to read in more detail how demuxmix works.
