### ISSUE TITLE
modelling VDJ 2 chain counts

### ISSUE THREAD

**Issue by avilella** [huklein/demuxmix#8]
Hi,

Would it be possible for demuxmix to model the HTO data together with VDJ data, rather than GEX data, where 
 for VDJ data there are RNA (UMI) counts for the number of times 2 chains (i.e. BCR or TCR genes) are found, e.g. for the BCR heavy chain and light chain?

E.g. there would be cases where a given barcode has one main HTO, and 2 chains (first table below), but there would be cases where the barcode has two HTOs and more than 2 chains (second table below):

Example where there is only u_cell1 and u_cell2 counts:

```
barcode              cspu1   cspu2   cspu3   cspu4   cspu5   cspu6   cspu7   cspu8   cspu9   cspu10   cspu11   u_cell1   u_cell2   u_cell3
------------------   -----   -----   -----   -----   -----   -----   -----   -----   -----   ------   ------   -------   -------   -------
AGTCTTTTCGTTGCCT-1   0       0       0       713     14      0       0       0       0       0        0        43        74        0
TATGCCCCAATGAATG-1   0       0       0       8       587     0       0       0       0       0        0        16        15        0
TACACGAGTATATGAG-1   0       0       0       605     10      0       0       0       0       0        0        7         24        0
TCTTTCCAGTACATGA-1   0       0       0       471     6       0       0       0       0       0        0        11        15        0
ATCCGAATCATTCACT-1   0       0       0       302     5       0       0       0       0       0        0        6         7         0
TTGCCGTCAAGGTTCT-1   0       0       0       659     28      0       0       0       0       0        0        14        32        0
GTCGTAAGTCCCTTGT-1   0       0       0       597     9       0       0       0       0       0        0        14        20        0
GTATCTTCACATCTTT-1   0       0       0       613     15      0       0       0       0       0        0        7         20        0
GTAACTGAGGTAGCTG-1   0       0       0       23      407     0       0       0       0       0        0        15        12        0

```

Example where u_cell3 is non-zero:

```
barcode              cspu1   cspu2   cspu3   cspu4   cspu5   cspu6   cspu7   cspu8   cspu9   cspu10   cspu11   u_cell1   u_cell2   u_cell3
------------------   -----   -----   -----   -----   -----   -----   -----   -----   -----   ------   ------   -------   -------   -------
TCTATTGGTATGAATG-1   1       0       0       538     237     0       0       0       0       0        0        16        20        17
CGGACACAGAATTGTG-1   1       0       0       627     346     0       0       0       0       0        0        30        33        11
GCGGGTTAGCCAACAG-1   0       0       0       979     182     0       0       0       0       0        0        19        15        35
GACGGCTGTGACAAAT-1   0       0       0       370     367     0       0       0       0       0        0        41        27        61
ATTTCTGAGAACTCGG-1   0       1       0       495     299     0       0       0       0       0        0        41        22        38
CTCGTCATCGCTTGTC-1   0       0       0       375     6       0       0       0       0       0        0        18        16        30
GCATGCGCAGGTCTCG-1   0       0       0       566     34      0       0       0       0       0        0        18        19        15
ATTGGACAGCTTATCG-1   0       0       0       742     11      0       0       0       0       0        0        5         18        24
CTACGTCAGATACACA-1   0       0       0       482     26      0       0       0       0       0        0        9         11        20

```

Thanks in advance

**Comment by huklein** [comment]
Hi,
I will break up your comment into two questions:
i) Can demuxmix be used with VDJ data instead of RNA data?
ii) Can demuxmix be used if cells were tagged with two (or more) HTOs?

Ad i)
That is an interesting thought; I have not had the chance to work with hashed V(D)J data, so I am not sure. It depends on whether you see an association between the number of HTO counts and the number of reads in the V(D)J library (or the number of different clonotypes). If there is a linear association, I would expect adding this information as a covariate should improve demultiplexing. See Figure 1B in the preprint of how it looks like for RNA data (https://www.biorxiv.org/content/10.1101/2023.01.27.525961v1). Cell size is the main driver for this association with the RNA data. Larger cells have a larger surface for HTO antibodies to bind and also more RNA content. The association is much weaker if a sample consists of homogeneous cells from a cell line. I don't think  such an association can be expected for VDJ data(?)
However, demuxmix can run without the 'rna' parameter by setting model='naive'. That will definitely work for VDJ single-cell data.

Ad ii)
Yes, that is no problem for demuxmix. When you look at the output of dmmClassify(), the first column will show all HTOs detected for that droplet. You will find many entries labeled 'cspu4,cspu5' in your example. The only downside when using combinations of HTOs to tag cells is that the summary() method reports those cells as doublets. So you will have to generate your own summary from the dmmClassify output.
I have been asked this question before, and if many people use such experimental designs, I may add a parameter to the summary method to make it more flexible. (Although I mainly see disadvantages of using combinations of HTOs to tag cells.)
